version: "3.9"

services:
  go_api:
    container_name: go_api
    image: go-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: go_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
